### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by ELMIAR-0642** [weng-lab/libzdock#6]
Upon running ```make test```, I get the folloing error:

`make test`

> g++ -march=native -O3 -std=c++14 -DEIGEN_USE_LAPACKE -Wall -pedantic  -DDATADIR=/home/randd/Desktop/Desktop_Office/October2023/SecondWeek/Docking_Benchmark/ZDock/libzdock/test/data -Icontrib/Catch2/single_include -Icontrib/eigen -Isrc/libpdb++ -Isrc/zdock -Isrc/common -Isrc/pdb -Iinclude -c -o build/test/prediction.o test/prediction.cpp
> In file included from test/prediction.cpp:31:
> test/Test.hpp:32:10: fatal error: catch2/catch.hpp: No such file or directory
>    32 | #include "catch2/catch.hpp"
>       |          ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:59: build/test/prediction.o] Error 1

**Comment by arjanvandervelde** [comment]
Looks like Catch is not longer header-only starting at v3. I'm fixing the submodule to v2.13.10 for now.
